"""init bookings

Revision ID: e756e7c7c7dd
Revises: 672db734a059
Create Date: 2026-06-17 16:46:54.680929

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e756e7c7c7dd'
down_revision: str | Sequence[str] | None = '672db734a059'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
